### ISSUE TITLE
Make travis run some system and module tests

### ISSUE THREAD

**Issue by franchoco** [niclabs/tchsm-libdtc#73] opened 2016-06-16 20:25 UTC
Total run time must not exceed 6 minutes.

**Comment by fmontoto** [comment] 2016-06-24 20:22
There is an unexpected behaviour of the system test´s at Travis.

**Comment by raticate** [comment] 2016-12-15 17:56
the problem was fixed within tchsm-libtc. Tests where added in #126

**Closed by raticate** 2016-12-15 17:56 UTC
